//Write your function calls below this line
//Four Corners!
//setColor(0, 0, "purple");
//setcolor(0, 9, "purple");
//setColor(9, 0, "purple");
//setColor(9, 9, "purple");

//Smiley Face!
//setColor(2, 2, "black");
//setColor(2, 6, "black");
//setColor(6, 1, "black");
//setColor(7, 2, "black");
//setColor(8, 3, "black");
//setColor(8, 4, "black");
//setColor(8, 5, "black");
//setColor(7, 6, "black");
//setColor(6, 7, "black");
//setColor(6, 7, "black");
//setColor(5, 4, "black");

//The Letter S!
//setColor(2, 7, "black");
//setColor(1, 6, "black");
//setColor(1, 5, "black");
//setColor(1, 4, "black");
//setColor(1, 3, "black");
//setColor(2, 2, "black");
//setColor(3, 3, "black");
//setColor(4, 4, "black");
//setColor(5, 5, "black");
//setColor(6, 6, "black");
//setColor(7, 5, "black");
//setColor(7, 4, "black");
//setColor(7, 3, "black");
//setColor(7, 2, "black");
//setColor(6, 1, "red");

//A Flag!
setColor(0, 0, "blue");
setColor(1, 0, "blue");
setColor(2, 0, "blue");
setColor(3, 0, "blue");
setColor(4, 0, "blue");
setColor(5, 0, "blue");
setColor(6, 0, "blue");
setColor(7, 0, "blue");
setColor(8, 0, "blue");
setColor(9, 0, "blue");
setColor(0, 1, "blue");
setColor(1, 1, "blue");
setColor(2, 1, "blue");
setColor(3, 1, "blue");
setColor(4, 1, "blue");
setColor(5, 1, "blue");
setColor(6, 1, "blue");
setColor(7, 1, "blue");
setColor(8, 1, "blue");
setColor(9, 1, "blue");
setColor(0, 2, "blue");
setColor(1, 2, "blue");
setColor(2, 2, "blue");
setColor(3, 2, "blue");
setColor(4, 2, "blue");
setColor(5, 2, "blue");
setColor(6, 2, "blue");
setColor(7, 2, "blue");
setColor(8, 2, "blue");
setColor(9, 2, "blue");
setColor(0, 7, "red")
setColor(1, 7, "red")
setColor(2, 7, "red")
setColor(3, 7, "red")
setColor(4, 7, "red")
setColor(5, 7, "red")
setColor(6, 7, "red")
setColor(7, 7, "red")
setColor(8, 7, "red")
setColor(9, 7, "red")
setColor(0, 8, "red")
setColor(1, 8, "red")
setColor(2, 8, "red")
setColor(3, 8, "red")
setColor(4, 8, "red")
setColor(5, 8, "red")
setColor(6, 8, "red")
setColor(7, 8, "red")
setColor(8, 8, "red")
setColor(9, 8, "red")
setColor(0, 9, "red")
setColor(1, 9, "red")
setColor(2, 9, "red")
setColor(3, 9, "red")
setColor(4, 9, "red")
setColor(5, 9, "red")
setColor(6, 9, "red")
setColor(7, 9, "red")
setColor(8, 9, "red")
setColor(9, 9, "red")
